### ISSUE TITLE
Compiler related performance issues in target code generation

### ISSUE THREAD

**Issue by sithhell** [allscale/allscale_compiler#8]
This is supposed to be meta ticket to track compiler related performance problems in combination with the allscale runtime we identified so far.

 - [x] https://github.com/allscale/allscale_compiler/issues/6 Compiler should not use treeture<void> in process variants
 - [x] https://github.com/allscale/allscale_compiler/issues/7 `DataItemManager::get` is not supposed be used in tight loops
 - [ ] https://github.com/allscale/allscale_compiler/issues/9 Compiler should not use treeture<T> in process variants

Please check the boxes once the fixes have landed on master and amend the list once new issues have been found.
